// ─── Severidade ────────────────────────────────────────────────────────────
export const SEVERITY = {
  CRITICAL: {
    label:  "Crítico",
    badge:  "bg-red-100 text-red-700 border border-red-200",
    dot:    "bg-red-500",
    text:   "text-red-600",
    row:    "bg-red-50/60",
    border: "border-red-200",
    icon:   "●",
  },
  HIGH: {
    label:  "Alto",
    badge:  "bg-orange-100 text-orange-700 border border-orange-200",
    dot:    "bg-orange-500",
    text:   "text-orange-600",
    row:    "bg-orange-50/60",
    border: "border-orange-200",
    icon:   "●",
  },
  MEDIUM: {
    label:  "Médio",
    badge:  "bg-yellow-100 text-yellow-700 border border-yellow-200",
    dot:    "bg-yellow-500",
    text:   "text-yellow-600",
    row:    "bg-yellow-50/40",
    border: "border-yellow-200",
    icon:   "●",
  },
  LOW: {
    label:  "Baixo",
    badge:  "bg-blue-100 text-blue-600 border border-blue-200",
    dot:    "bg-blue-400",
    text:   "text-blue-500",
    row:    "bg-blue-50/30",
    border: "border-blue-200",
    icon:   "●",
  },
};

export const PIPELINES = [
  { value: "all", label: "Completo",   desc: "Todos os pipelines (1 + 2 + 3 + 4)" },
  { value: "1",   label: "Pipeline 1", desc: "WHOIS · DNS · SSL · OSINT · Nmap"   },
  { value: "2",   label: "Pipeline 2", desc: "WAF · Crawler · API Fuzzer · GraphQL"},
  { value: "3",   label: "Pipeline 3 (IA)", desc: "JWT · IDOR · Secrets · XSS · SQLi" },
  { value: "4",   label: "Pipeline 4", desc: "Exploração automática de findings"   },
  { value: "6",   label: "Gemini AI",  desc: "Gemini Active Attacker"              },
];

// ─── Mock data (usado quando API está offline) ────────────────────────────
export const MOCK_REPORTS = [
  { id: "r1", filename: "example_com_report.json", target: "https://example.com",           date: "2025-05-04", pipeline: "all", findings: 14, critical: 3, high: 5, medium: 4, low: 2 },
  { id: "r2", filename: "vulnweb_report.json",     target: "https://testphp.vulnweb.com",   date: "2025-05-02", pipeline: "3",   findings: 22, critical: 6, high: 8, medium: 5, low: 3 },
  { id: "r3", filename: "juiceshop_report.json",   target: "https://juiceshop.local",       date: "2025-04-30", pipeline: "1",   findings: 9,  critical: 1, high: 3, medium: 3, low: 2 },
];

export const MOCK_FINDINGS = [
  { id: 1, severity: "CRITICAL", title: "SQL Injection em /api/login",        source: "AI Engine",         url: "/api/login",    cvss: 9.8, description: "Parâmetro `user` vulnerável a SQLi básico. Payload `' OR 1=1--` retornou dados sensíveis.", recommendation: "Use prepared statements / ORM parametrizado. Nunca concatene input do usuário em queries SQL." },
  { id: 2, severity: "CRITICAL", title: "XSS Refletido em campo de busca",    source: "AI Engine",         url: "/search?q=",    cvss: 8.2, description: "Input não sanitizado refletido diretamente no DOM sem encoding. Permite execução arbitrária de JS.", recommendation: "Escape output com bibliotecas como DOMPurify. Implemente Content-Security-Policy restritivo." },
  { id: 3, severity: "CRITICAL", title: "JWT com alg:none aceito",            source: "JWT Analyzer",      url: "/api/auth",     cvss: 9.1, description: "Servidor aceita tokens JWT sem assinatura (algoritmo `none`), permitindo forjamento de sessão.", recommendation: "Valide explicitamente o algoritmo no backend. Rejeite tokens com alg:none ou algorítmos simétricos fracos." },
  { id: 4, severity: "HIGH",     title: "IDOR em /api/user/{id}",             source: "IDOR Tester",       url: "/api/user/42",  cvss: 7.5, description: "Endpoint expõe dados de outros usuários sem validação de autorização baseada em identidade.", recommendation: "Implemente ABAC/RBAC. Valide que o usuário autenticado tem permissão para acessar o recurso requisitado." },
  { id: 5, severity: "HIGH",     title: "Clickjacking possível",              source: "Clickjacking",      url: "/",             cvss: 6.1, description: "Header X-Frame-Options ausente. Página pode ser embutida em iframe malicioso para ataques de UI Redressing.", recommendation: "Adicione: X-Frame-Options: DENY ou Content-Security-Policy: frame-ancestors 'none'" },
  { id: 6, severity: "HIGH",     title: "Subdomínio takeover detectado",      source: "Subdomain Enum",    url: "dev.example.com", cvss: 7.2, description: "CNAME aponta para serviço não provisionado (GitHub Pages). Atacante pode reivindicar o subdomínio.", recommendation: "Remova o registro DNS ou provisione o serviço. Audite subdomínios regularmente." },
  { id: 7, severity: "MEDIUM",   title: "Cookie sem flag HttpOnly",           source: "Plugin:cookie",     url: "/",             cvss: 5.4, description: "Cookie de sessão `PHPSESSID` acessível via JavaScript. Facilita roubo de sessão via XSS.", recommendation: "Adicione a flag HttpOnly em todos os cookies de sessão: Set-Cookie: id=...; HttpOnly; Secure; SameSite=Strict" },
  { id: 8, severity: "MEDIUM",   title: "TLS 1.0 habilitado",                source: "SSL Analyzer",      url: ":443",          cvss: 4.3, description: "Servidor aceita TLS 1.0 (deprecated desde 2020). Vulnerável a ataques POODLE e BEAST.", recommendation: "Desabilite TLS 1.0 e 1.1. Configure apenas TLS 1.2+ com cipher suites modernas." },
  { id: 9, severity: "LOW",      title: "Server header exposto",              source: "Headers Check",     url: "/",             cvss: 2.7, description: "Header `Server: Apache/2.4.51` revela versão exata, facilitando busca por CVEs específicos.", recommendation: "Configure ServerTokens Prod no Apache ou server_tokens off no Nginx." },
];

export const MOCK_SCAN_LOG = [
  "[INFO]  Iniciando scan em https://example.com",
  "[INFO]  Pipeline: all",
  "[CRIT]  ━━━ PIPELINE 1: TRADICIONAL ━━━━━━━━━━━━━━━━━━━━━",
  "[INFO]  [1/6] Recon Passivo",
  "[OK]    WHOIS coletado · Registrar: MarkMonitor Inc.",
  "[OK]    DNS: A=93.184.216.34  MX=mail.example.com  NS=a.iana-servers.net",
  "[INFO]  [2/6] Recon Ativo (Nmap + Gobuster)",
  "[OK]    Nmap: portas abertas → 80/tcp  443/tcp  8080/tcp",
  "[OK]    Gobuster: 12 diretórios encontrados (/admin /api /backup /static ...)",
  "[INFO]  [3/6] SSL/TLS Analysis",
  "[WARN]  TLS 1.0 habilitado (deprecated) — risco MEDIUM",
  "[OK]    Certificado válido até 2026-01-15 · CN=example.com",
  "[INFO]  [4/6] Subdomain Enumeration",
  "[WARN]  Possível takeover: dev.example.com → GitHub Pages não provisionado",
  "[OK]    12 subdomínios ativos mapeados",
  "[INFO]  [5/6] OSINT Enrichment",
  "[OK]    Shodan: 3 CVEs para Apache 2.4.49",
  "[OK]    urlscan.io: reputação limpa",
  "[INFO]  [6/6] Scanner (CORS + Open Redirect)",
  "[WARN]  CORS misconfiguration: Access-Control-Allow-Origin: *",
  "[CRIT]  ━━━ PIPELINE 2: AGRESSIVO ━━━━━━━━━━━━━━━━━━━━━━━",
  "[INFO]  [1/8] WAF Fingerprinting",
  "[OK]    Nenhum WAF detectado — scan sem throttling",
  "[INFO]  [2/8] Crawler profundo",
  "[OK]    40 páginas rastreadas · 8 formulários encontrados",
  "[INFO]  [3/8] Motor Agressivo (Path Traversal + JS endpoints)",
  "[WARN]  Path traversal detectado: /download?file=../../../../etc/passwd",
  "[OK]    23 endpoints extraídos de arquivos JS minificados",
  "[INFO]  [4/8] API Fuzzer",
  "[OK]    3 endpoints não documentados: /api/v2/admin  /api/debug  /api/internal",
  "[INFO]  [5/8] GraphQL Tester",
  "[WARN]  Introspection exposta em /graphql — schema completo acessível",
  "[INFO]  [6/8] Clickjacking Tester",
  "[WARN]  X-Frame-Options ausente em 3 páginas",
  "[INFO]  [7/8] Rate Limit Tester",
  "[WARN]  /api/login sem rate limiting — brute force possível",
  "[INFO]  [8/8] Plugins (Headers · Cookies · CSP)",
  "[WARN]  Cookie PHPSESSID sem HttpOnly",
  "[WARN]  Content-Security-Policy ausente",
  "[CRIT]  ━━━ PIPELINE 3: IA ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
  "[INFO]  [1/5] JWT Analyzer",
  "[CRIT]  JWT com alg:none aceito! Autenticação completamente bypassável.",
  "[CRIT]  Token sem claim `exp` — sessões nunca expiram",
  "[INFO]  [2/5] IDOR Tester",
  "[CRIT]  IDOR confirmado: /api/user/42 retornou dados de usuário diferente",
  "[INFO]  [3/5] CVE Lookup por tecnologia",
  "[OK]    CVE-2021-41773 (Apache 2.4.49) — Path Traversal / RCE — CVSS 9.8",
  "[INFO]  [4/5] AI Engine (Secrets + XSS + SQLi + SSRF)",
  "[CRIT]  SQLi confirmado em /api/login — dump de dados possível",
  "[CRIT]  XSS refletido em /search?q= — payload: <script>alert(1)</script>",
  "[OK]    Secret scanner: 12 padrões verificados — 0 secrets expostos em HTML",
  "[INFO]  [5/5] Gerando Relatórios",
  "[OK]    PDF       → reports/example_com_report.pdf",
  "[OK]    Dashboard → reports/example_com_dashboard.html",
  "[OK]    JSON      → reports/example_com_report.json",
  "[SUCCESS] ━━━ VARREDURA FINALIZADA — 14 findings (3 críticos · 5 altos) ━━━",
];

export const MOCK_AI_INSIGHTS = [
  "JWT com alg:none é o vetor de maior risco — bypass completo de autenticação, corrija imediatamente.",
  "3 endpoints sem rate limiting detectados — alto risco de credential stuffing e brute force.",
  "Subdomain takeover em dev.example.com representa exposição lateral crítica ao ambiente de produção.",
  "Apache 2.4.49 possui CVE-2021-41773 público (CVSS 9.8) — atualização é urgente.",
  "Combinação SQLi + IDOR sugere ausência de camada de autorização centralizada no backend.",
];
